name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [Debug, Release]

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.0

      - name: CMake
        run: |
          $env:BOOST_ROOT = $env:BOOST_ROOT_1_72_0
          cmake -G "Visual Studio 16 2019" -A x64 -S . -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.mode }} --target http-client net-web_server-sample net-wss_client-sample
